config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :categories
  
  get "/product_list" => "products#product_list"

  get 'products/product_list'

    devise_scope :user do
    authenticated :user do
    root :to => 'categories#new', as: :authenticated_root
  end
  unauthenticated :user do
    root :to => 'devise/registrations#new', as: :unauthenticated_root
  end
end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_filter :authenticate_user!

	def new
		@category = Category.new
	end

	def index
		@categories = Category.all
	end

	def create
		@category = Category.new(category_params)
       if @category.save
       	flash[:notice] = "Category Saved Successfully"
       	redirect_to :controller => "products", :action => "new"
       else
       	flash[:notice] = "Error"
       	render "new"
       end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update_attribute(category_params)
			flash[:notice] = "Category Updated Successfully"
			redirect_to :controller => "categories", :action => "index"
		else
			render "edit"
		end
	end

	def destroy
	end

private
	def category_params
		params.require(:category).permit(:name,:about)
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
def new
		#@category = []
		#@user = []
		@product = Product.new
	end

	def index
		@products = Product.all
	end

	def create
		@product = Product.new(product_params)
       if @product.save
       	flash[:notice] = "product Saved Successfully"
       	redirect_to :controller => "products", :action => "product_list"
       else
       	flash[:notice] = "Error"
       	render "new"
       end
	end
            
	def edit
		@product = Product.find(params[:id])
	end

	def destroy
	end

	def show
	end

	def product_list
		#@product = Product.find(params[:id])
		@products = Product.all
		#@product = Product.where(params[:id]).all
        #render :partial => "product", :object => @product
	end

	def update_users
    product = Product.find(params[:user_id])
     @user = User.find(:all,:conditions => ["product_id = ?", product.id])
        
        #district = District.find(:all,:conditions=>["state_id = ?",state.id])
        #@area = Area.find(:all,:conditions=>["district_id = ?", district.id])
        #@state = State.find_all_by_country_id(category.id)
        render :update do |page|
             page.replace_html 'user_order1', :partial => 'user_order', :object => @user
        end
   end

   def update_category
       product = Product.find(params[:cat_id])
       @cat = Category.find(:all,:conditions => ["product_id = ?", product.id]) 
       
       render :update do |page|
        page.replace_html 'cat_order1', :partial => 'cat_order', :object => @cat
       end
   end 
	
	private
	def product_params
		params.require(:product).permit(:user_id,:category_id,:name,:cost)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<div class="jumbotron text-center">
<h1 align="center">New Categories</h1>
</div>

<div class="container">
 <%= form_for @category do |c| %>
	
	<div class="form-group">
  	<%= c.label :name %>
  </div>
  <div class="form-group">
  	<%= c.text_field :name, :required => true %> </br>
	</div>

	<div class="form-group">
		<%= c.label :about %>
	</div>
  <div class="form-group">
		<%= c.text_field :about, :required => true %>
	</div>

  <div class="action">
  	<%= c.submit "Save Category"%>
  </div>
  
  <%end%>
</div>

<style type="text/css">
  body
  {
    background-color: green;
  }
  .form-group
  {
    margin-left: 650px;
    padding: -10px;
    margin-top: 60px;
  }
  .action
  {
    margin-left: 680px;
    margin-top: 20px;
  }
</style>

app/views/categories/index.html.erb
<div class="table">

 <table>
 	<thead>
 		<tr>
		 	<th>Name</th>
		 	<th>About</th>
 		</tr>
 	</thead>
 <tbody>
 <% @categories.each do |c| %>
 	<tr>
	 	<td><%= c.name %></td>
	 	<td><%= c.about %></td>
	 	<td><%#= link_to 'Show', category %></td>
        <td><%#= link_to 'Edit', edit_category_path(category) %></td>
        <td><%#= link_to 'Destroy', categories, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 	</tr>
 <%end%>
 </tbody>
</table>
</div>

app/views/categories/new.html.erb
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Software</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<!-- <ul class="nav navbar-nav pull-right">
        <%# if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%#= current_user.email %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%#= link_to 'Profile', edit_user_registration_path %></li>
              <li><%#= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <%# else %>
          <li><%#= link_to 'Log In', new_user_session_path %></li>
          <li><%#= link_to 'Sign Up', new_user_registration_path %></li>
        <%# end %>
      </ul>
 -->
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<div class="jumbotron text-center">
<h1 align="center">New Projects</h1>
</div>

<div class="container">
 <%= form_for Product.new do |c| %>
	
  <div class="label-field">
  	<%= c.label :user_id %>
  </div>

  <div class="text-field">
  	<%#= c.collection_select(:product, :user_id, User.all, :id, :email)%>
  	<%= c.select :user_id, User.all.collect {|x| [x.email, x.id]}, :prompt => "Please Select" %>
  </div>

  <div class="label-field">
  	<%= c.label :category_id %>
  </div>

  <div class="text-field">
  <%= c.select :category_id, Category.all.collect {|x| [x.name, x.id]}, :prompt => "Please Select"%>
  	<%#= c.collection_select(:product, :cat_id, Category.all, :id, :name)%>
  </div>

  <div class="label-field">
  	<%= c.label :name %>
  </div>
  <div class="text-field">
  	<%= c.text_field :name, :required => true %> </br>
	</div>

	<div class="label-field">
		<%= c.label :cost %>
	</div>
  <div class="text-field">
		<%= c.text_field :cost, :required => true %>
	</div>

  <div class="action">
  	<%= c.submit "Save Products"%>
  </div>
  
  <%end%>
</div>

<style type="text/css">
  body
  {
    background-color: green; 
  }
  .container
  {
    width: 600px;
    text-align: center;
    margin-left: 300px;
  }
  .text-field
  {
    margin-top: 0px;
    width: 1000px;
  }
  .label-field
  {
    padding: 20px;
    width: 500px;
  }
</style>

app/views/products/_product.html.erb
<table id="table" class="table table-bordered table-stripped">
	<thead>
		<tr>
			<th>Projects</th>
			<th>Username</th>
			<th>Category Name</th>
		</tr>
	</thead>
	<%= @products.each do |p|%>
	<tbody>
		<tr>
			<td></td>
		</tr>
	</tbody>
</table>

app/views/products/new.html.erb
<%= render "form" %>

app/views/products/product_list.html.erb
<!-- <script type="text/javascript" src="path_to/jquery.js"></script>
<script type="text/javascript" src="path_to/jquery.simplePagination.js"></script>
<link type="text/css" rel="stylesheet" href="path_to/simplePagination.css"/>
 -->
<% if user_signed_in? %>
	<b> User:</b><%= current_user.email %>
	<li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
<%end%>

<!-- <script src="//code.jquery.com/jquery.min.js"></script>
<script src="paginate.js"></script> -->
<div id="pager">
<table id="table" class="table table-bordered table-stripped">
	<thead>
		<tr>
		   <th>SI No</th>
			<th>Projects</th>
			<th>Username</th>
			<th>Category Name</th>
		</tr>
	</thead>
	<%count = 0%>
	<tbody>
	<% @products.each do |p|%>
		<tr>
		    <td><%= count = count + 1%></td>
			<td><%= p.name%></td>
			<td><%= p.user.email%></td>
			<td><%= p.category.name%></td>
		</tr>
	</tbody>
	<%end%>
</table>
</div>
<!-- <div class="pagination"></div> -->
<!-- 
<script type="text/javascript">
$.noConflict();
jQuery(function ($) { 
    $("table") 
    .tablesorter({widthFixed: true, widgets: ['zebra'] }) 
    .tablesorterPager({
        container: $("#pager"),
        size:5
    }); 
});
 </script> -->
 <style type="text/css">
 	body
 	{
 		background-color: green;
 	}
 	#pager
 	{
 		margin-left: 500px;
 		margin-top: 200px;
 	}
 </style>

<!--  <script type="text/javascript">
 	$(function() {
    $(selector).pagination({
        items: 100,
        itemsOnPage: 10,
        cssStyle: 'light-theme'
    });
});
 </script> -->
 <script type="text/javascript">
 	
(function($){

	var methods = {
		init: function(options) {
			var o = $.extend({
				items: 1,
				itemsOnPage: 1,
				pages: 0,
				displayedPages: 5,
				edges: 2,
				currentPage: 0,
				useAnchors: true,
				hrefTextPrefix: '#page-',
				hrefTextSuffix: '',
				prevText: 'Prev',
				nextText: 'Next',
				ellipseText: '&hellip;',
				ellipsePageSet: true,
				cssStyle: 'light-theme',
				listStyle: '',
				labelMap: [],
				selectOnClick: true,
				nextAtFront: false,
				invertPageOrder: false,
				useStartEdge : true,
				useEndEdge : true,
				onPageClick: function(pageNumber, event) {
					// Callback triggered when a page is clicked
					// Page number is given as an optional parameter
				},
				onInit: function() {
					// Callback triggered immediately after initialization
				}
			}, options || {});

			var self = this;

			o.pages = o.pages ? o.pages : Math.ceil(o.items / o.itemsOnPage) ? Math.ceil(o.items / o.itemsOnPage) : 1;
			if (o.currentPage)
				o.currentPage = o.currentPage - 1;
			else
				o.currentPage = !o.invertPageOrder ? 0 : o.pages - 1;
			o.halfDisplayed = o.displayedPages / 2;

			this.each(function() {
				self.addClass(o.cssStyle + ' simple-pagination').data('pagination', o);
				methods._draw.call(self);
			});

			o.onInit();

			return this;
		},

		selectPage: function(page) {
			methods._selectPage.call(this, page - 1);
			return this;
		},

		prevPage: function() {
			var o = this.data('pagination');
			if (!o.invertPageOrder) {
				if (o.currentPage > 0) {
					methods._selectPage.call(this, o.currentPage - 1);
				}
			} else {
				if (o.currentPage < o.pages - 1) {
					methods._selectPage.call(this, o.currentPage + 1);
				}
			}
			return this;
		},

		nextPage: function() {
			var o = this.data('pagination');
			if (!o.invertPageOrder) {
				if (o.currentPage < o.pages - 1) {
					methods._selectPage.call(this, o.currentPage + 1);
				}
			} else {
				if (o.currentPage > 0) {
					methods._selectPage.call(this, o.currentPage - 1);
				}
			}
			return this;
		},

		getPagesCount: function() {
			return this.data('pagination').pages;
		},

		setPagesCount: function(count) {
			this.data('pagination').pages = count;
		},

		getCurrentPage: function () {
			return this.data('pagination').currentPage + 1;
		},

		destroy: function(){
			this.empty();
			return this;
		},

		drawPage: function (page) {
			var o = this.data('pagination');
			o.currentPage = page - 1;
			this.data('pagination', o);
			methods._draw.call(this);
			return this;
		},

		redraw: function(){
			methods._draw.call(this);
			return this;
		},

		disable: function(){
			var o = this.data('pagination');
			o.disabled = true;
			this.data('pagination', o);
			methods._draw.call(this);
			return this;
		},

		enable: function(){
			var o = this.data('pagination');
			o.disabled = false;
			this.data('pagination', o);
			methods._draw.call(this);
			return this;
		},

		updateItems: function (newItems) {
			var o = this.data('pagination');
			o.items = newItems;
			o.pages = methods._getPages(o);
			this.data('pagination', o);
			methods._draw.call(this);
		},

		updateItemsOnPage: function (itemsOnPage) {
			var o = this.data('pagination');
			o.itemsOnPage = itemsOnPage;
			o.pages = methods._getPages(o);
			this.data('pagination', o);
			methods._selectPage.call(this, 0);
			return this;
		},

		getItemsOnPage: function() {
			return this.data('pagination').itemsOnPage;
		},

		_draw: function() {
			var	o = this.data('pagination'),
				interval = methods._getInterval(o),
				i,
				tagName;

			methods.destroy.call(this);

			tagName = (typeof this.prop === 'function') ? this.prop('tagName') : this.attr('tagName');

			var $panel = tagName === 'UL' ? this : $('<ul' + (o.listStyle ? ' class="' + o.listStyle + '"' : '') + '></ul>').appendTo(this);

			// Generate Prev link
			if (o.prevText) {
				methods._appendItem.call(this, !o.invertPageOrder ? o.currentPage - 1 : o.currentPage + 1, {text: o.prevText, classes: 'prev'});
			}

			// Generate Next link (if option set for at front)
			if (o.nextText && o.nextAtFront) {
				methods._appendItem.call(this, !o.invertPageOrder ? o.currentPage + 1 : o.currentPage - 1, {text: o.nextText, classes: 'next'});
			}

			// Generate start edges
			if (!o.invertPageOrder) {
				if (interval.start > 0 && o.edges > 0) {
					if(o.useStartEdge) {
						var end = Math.min(o.edges, interval.start);
						for (i = 0; i < end; i++) {
							methods._appendItem.call(this, i);
						}
					}
					if (o.edges < interval.start && (interval.start - o.edges != 1)) {
						$panel.append('<li class="disabled"><span class="ellipse">' + o.ellipseText + '</span></li>');
					} else if (interval.start - o.edges == 1) {
						methods._appendItem.call(this, o.edges);
					}
				}
			} else {
				if (interval.end < o.pages && o.edges > 0) {
					if(o.useStartEdge) {
						var begin = Math.max(o.pages - o.edges, interval.end);
						for (i = o.pages - 1; i >= begin; i--) {
							methods._appendItem.call(this, i);
						}
					}

					if (o.pages - o.edges > interval.end && (o.pages - o.edges - interval.end != 1)) {
						$panel.append('<li class="disabled"><span class="ellipse">' + o.ellipseText + '</span></li>');
					} else if (o.pages - o.edges - interval.end == 1) {
						methods._appendItem.call(this, interval.end);
					}
				}
			}

			// Generate interval links
			if (!o.invertPageOrder) {
				for (i = interval.start; i < interval.end; i++) {
					methods._appendItem.call(this, i);
				}
			} else {
				for (i = interval.end - 1; i >= interval.start; i--) {
					methods._appendItem.call(this, i);
				}
			}

			// Generate end edges
			if (!o.invertPageOrder) {
				if (interval.end < o.pages && o.edges > 0) {
					if (o.pages - o.edges > interval.end && (o.pages - o.edges - interval.end != 1)) {
						$panel.append('<li class="disabled"><span class="ellipse">' + o.ellipseText + '</span></li>');
					} else if (o.pages - o.edges - interval.end == 1) {
						methods._appendItem.call(this, interval.end);
					}
					if(o.useEndEdge) {
						var begin = Math.max(o.pages - o.edges, interval.end);
						for (i = begin; i < o.pages; i++) {
							methods._appendItem.call(this, i);
						}
					}
				}
			} else {
				if (interval.start > 0 && o.edges > 0) {
					if (o.edges < interval.start && (interval.start - o.edges != 1)) {
						$panel.append('<li class="disabled"><span class="ellipse">' + o.ellipseText + '</span></li>');
					} else if (interval.start - o.edges == 1) {
						methods._appendItem.call(this, o.edges);
					}

					if(o.useEndEdge) {
						var end = Math.min(o.edges, interval.start);
						for (i = end - 1; i >= 0; i--) {
							methods._appendItem.call(this, i);
						}
					}
				}
			}

			// Generate Next link (unless option is set for at front)
			if (o.nextText && !o.nextAtFront) {
				methods._appendItem.call(this, !o.invertPageOrder ? o.currentPage + 1 : o.currentPage - 1, {text: o.nextText, classes: 'next'});
			}

			if (o.ellipsePageSet && !o.disabled) {
				methods._ellipseClick.call(this, $panel);
			}

		},

		_getPages: function(o) {
			var pages = Math.ceil(o.items / o.itemsOnPage);
			return pages || 1;
		},

		_getInterval: function(o) {
			return {
				start: Math.ceil(o.currentPage > o.halfDisplayed ? Math.max(Math.min(o.currentPage - o.halfDisplayed, (o.pages - o.displayedPages)), 0) : 0),
				end: Math.ceil(o.currentPage > o.halfDisplayed ? Math.min(o.currentPage + o.halfDisplayed, o.pages) : Math.min(o.displayedPages, o.pages))
			};
		},

		_appendItem: function(pageIndex, opts) {
			var self = this, options, $link, o = self.data('pagination'), $linkWrapper = $('<li></li>'), $ul = self.find('ul');

			pageIndex = pageIndex < 0 ? 0 : (pageIndex < o.pages ? pageIndex : o.pages - 1);

			options = {
				text: pageIndex + 1,
				classes: ''
			};

			if (o.labelMap.length && o.labelMap[pageIndex]) {
				options.text = o.labelMap[pageIndex];
			}

			options = $.extend(options, opts || {});

			if (pageIndex == o.currentPage || o.disabled) {
				if (o.disabled || options.classes === 'prev' || options.classes === 'next') {
					$linkWrapper.addClass('disabled');
				} else {
					$linkWrapper.addClass('active');
				}
				$link = $('<span class="current">' + (options.text) + '</span>');
			} else {
				if (o.useAnchors) {
					$link = $('<a href="' + o.hrefTextPrefix + (pageIndex + 1) + o.hrefTextSuffix + '" class="page-link">' + (options.text) + '</a>');
				} else {
					$link = $('<span >' + (options.text) + '</span>');
				}
				$link.click(function(event){
					return methods._selectPage.call(self, pageIndex, event);
				});
			}

			if (options.classes) {
				$link.addClass(options.classes);
			}

			$linkWrapper.append($link);

			if ($ul.length) {
				$ul.append($linkWrapper);
			} else {
				self.append($linkWrapper);
			}
		},

		_selectPage: function(pageIndex, event) {
			var o = this.data('pagination');
			o.currentPage = pageIndex;
			if (o.selectOnClick) {
				methods._draw.call(this);
			}
			return o.onPageClick(pageIndex + 1, event);
		},


		_ellipseClick: function($panel) {
			var self = this,
				o = this.data('pagination'),
				$ellip = $panel.find('.ellipse');
			$ellip.addClass('clickable').parent().removeClass('disabled');
			$ellip.click(function(event) {
				if (!o.disable) {
					var $this = $(this),
						val = (parseInt($this.parent().prev().text(), 10) || 0) + 1;
					$this
						.html('<input type="number" min="1" max="' + o.pages + '" step="1" value="' + val + '">')
						.find('input')
						.focus()
						.click(function(event) {
							// prevent input number arrows from bubbling a click event on $ellip
							event.stopPropagation();
						})
						.keyup(function(event) {
							var val = $(this).val();
							if (event.which === 13 && val !== '') {
								// enter to accept
								if ((val>0)&&(val<=o.pages))
								methods._selectPage.call(self, val - 1);
							} else if (event.which === 27) {
								// escape to cancel
								$ellip.empty().html(o.ellipseText);
							}
						})
						.bind('blur', function(event) {
							var val = $(this).val();
							if (val !== '') {
								methods._selectPage.call(self, val - 1);
							}
							$ellip.empty().html(o.ellipseText);
							return false;
						});
				}
				return false;
			});
		}

	};

	$.fn.pagination = function(method) {

		// Method calling logic
		if (methods[method] && method.charAt(0) != '_') {
			return methods[method].apply(this, Array.prototype.slice.call(arguments, 1));
		} else if (typeof method === 'object' || !method) {
			return methods.init.apply(this, arguments);
		} else {
			$.error('Method ' +  method + ' does not exist on jQuery.pagination');
		}

	};

})(jQuery);
 </script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>